In [6]:
import numpy as np
arr = np.array([1, 2, 2, 3, 4, 4, 5,"chinnu","chinnu","Chinnu"])
arr1=np.unique(arr)
print(arr1)

['1' '2' '3' '4' '5' 'Chinnu' 'chinnu']


In [15]:
arr=[100,123,2,4,2,45,7,85,44]
arr2=np.sort(arr)
print(arr2)

arr=['chinnu','Chinnu','chanti',]
arr2=np.sort(arr)
print(arr2)

arr=['7','44', '45', '7', '85']
arr4=np.sort(arr)
print(arr4)

[  2   2   4   7  44  45  85 100 123]
['Chinnu' 'chanti' 'chinnu']
['44' '45' '7' '7' '85']


In [ ]:
arr=[100,123,2,4,2,45,7,85,44]
argsort=np.argsort(arr)
print(argsort) # Index sorting.

[2 4 3 6 8 5 7 0 1]


In [18]:
arr=[100,123,2,4,2,45,7,85,44]
count=np.count_nonzero(arr)
print(count)

arr=[100,0,2,4,2,45,0,85,44]
count=np.count_nonzero(arr)
print(count)

9
7


In [26]:
arr=[100,np.nan,2,np.nan,7,0]
nan=np.nan_to_num(arr)
print(nan)
nan=np.nan_to_num(arr,nan=1)
print(nan)

[100.   0.   2.   0.   7.   0.]
[100.   1.   2.   1.   7.   0.]


In [28]:
print(arr)
nanarr=np.isnan(arr)
print(nanarr)

[100, nan, 2, nan, 7, 0]
[False  True False  True False False]


In [30]:
arr=[100,np.nan,2,np.nan,7,0]
new_arr=np.delete(arr,1)
print(new_arr)
new_arr=np.delete(arr,0)
print(new_arr)

[100.   2.  nan   7.   0.]
[nan  2. nan  7.  0.]


In [31]:
ins=np.insert(arr,3,70)
print(ins)

[100.  nan   2.  70.  nan   7.   0.]
