In [8]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print()
print(arr[1,2])
print("Select a row")
print(arr[1])
print(arr[1,:]) 
print("Select Array greater then ")
print(arr[arr>5])
print(arr)
arr1=np.array([1,2,3])
             
print(arr1[[True,False,False]])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

6
Select a row
[4 5 6]
[4 5 6]
Select Array greater then 
[6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1]


In [9]:
print(arr)
arr1=np.where(arr>5,1,3)
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 3 3]
 [3 3 1]
 [1 1 1]]


In [10]:
arr=np.array([[0,2,3]])
print(np.nonzero(arr)) #This function returns the row and column indices of all non-zero values in an array.

# # (array([0, 0]), array([1, 2]))
# #    ↑             ↑
# #  rows          columns

# Meaning:
# Non-zero elements are at:
# (0,1)
# (0,2)

(array([0, 0]), array([1, 2]))


In [11]:
arr=np.array([[1,0,3],[4,5,0],[7,8,0]])
print(arr)

nonarr=np.nonzero(arr)
print(nonarr)

# Value	Position (row, col)
# 1	            (0, 0)
# 3	            (0, 2)
# 4	            (1, 0)
# 5	            (1, 1)
# 7	            (2, 0)
# 8	            (2, 1)
# Row indices (first array) :     [0, 0, 1, 1, 2, 2] --> all are rows indexes
# Column indices (second array) : [0, 2, 0, 1, 0, 1] --> All are colum indexes




[[1 0 3]
 [4 5 0]
 [7 8 0]]
(array([0, 0, 1, 1, 2, 2]), array([0, 2, 0, 1, 0, 1]))


In [12]:
arr=np.array([[1,0,3],[4,5,0],[7,8,0]])
print(arr)
print()
arr[0:2,:]=10
print(arr)


[[1 0 3]
 [4 5 0]
 [7 8 0]]

[[10 10 10]
 [10 10 10]
 [ 7  8  0]]


In [13]:
arr=np.array([[1,0,3],[4,5,0],[7,8,0]])
print(arr)
print()

print(arr[:,1:3])

[[1 0 3]
 [4 5 0]
 [7 8 0]]

[[0 3]
 [5 0]
 [8 0]]


In [ ]:
arr=np.array([[1,0,3],[4,5,0],[7,8,0]])
print(arr)
print()


[[1 0 3]
 [4 5 0]
 [7 8 0]]

