In [4]:
import numpy as np

arr = np.array([3,4])
print(arr)

[3 4]


In [5]:
mean=np.mean(arr)
print(mean)

3.5


In [7]:
arr1=np.array([[1,2],[3,4],[5,6]])
print(arr1)
mean1=np.mean(arr1)
print(mean1)

[[1 2]
 [3 4]
 [5 6]]
3.5


In [9]:
median=np.median(arr)
print(median)
print()
median1=np.median(arr1)
print(median1)

arr3=np.array([1,2,3])
median3=np.median(arr3)
print(median3)

3.5

3.5
2.0


In [10]:
print(arr1)
std1=np.std(arr1)
print(std1)
print()

print(arr3)
std3=np.std(arr3)
print(std3)
print()




[[1 2]
 [3 4]
 [5 6]]
1.707825127659933

[1 2 3]
0.816496580927726



In [11]:
print(arr1)
sum1=np.sum(arr1)
print(sum1)
print()

print(arr3)
sum3=np.sum(arr3)
print(sum3)
print()

[[1 2]
 [3 4]
 [5 6]]
21

[1 2 3]
6



In [15]:
arr=np.array([1,33,63,38,77,9,0,33])
print(arr)
print()
print(np.max(arr))

[ 1 33 63 38 77  9  0 33]

77


In [16]:
print(np.min(arr))

0


In [20]:
print(np.percentile(arr,50))
print(np.percentile(arr,0))
print(np.percentile(arr,60))
print(np.percentile(arr,100))


33.0
0.0
34.0
77.0


In [ ]:
print(np.var(arr)) # Variance

692.1875


In [22]:
#  Correlation coefficient between two arrays
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
print(np.corrcoef(arr1,arr2))

[[1. 1.]
 [1. 1.]]
