In [2]:
import numpy as np

arr1=np.array([[1,2],[3,4]])

arr2=np.array([[5,6],[7,8]])

print(arr1)
print()
print(arr2)
print()

arr3=np.dot(arr1,arr2)
arr4=np.matmul(arr1,arr2)
print(arr3)
print(arr4)
print(arr1@arr2)


[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [3]:
arr2=np.array([[5,6],[7,8]])
print(arr2)
print()
print(arr2.T)

[[5 6]
 [7 8]]

[[5 7]
 [6 8]]


In [9]:
arr=np.array([[1,2],[3,4]])
print(arr)
arr1=np.linalg.inv(arr)
print()
print(arr1)


[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [14]:
arr1=np.array([[1,2],[3,4]])
arr2=np.linalg.det(arr1)
print()
print(arr2)



-2.0000000000000004


In [15]:
arr1=np.array([[1,2],[2,4]])
print(arr1)
print()
arr2=np.linalg.det(arr1)
print(arr2)

[[1 2]
 [2 4]]

0.0


In [18]:
print(arr)
eigvalues,eigvector=np.linalg.eig(arr)
print()
print(eigvalues)
print()
print(eigvector)

[[1 2]
 [3 4]]

[-0.37228132  5.37228132]

[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [22]:
print(arr)
print()
U,S,Vh=np.linalg.svd(arr)
print(U)
print()
print(S)
print()
print(Vh)
print()



[[1 2]
 [3 4]]

[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]

[5.4649857  0.36596619]

[[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]



In [25]:
print(arr)
print()
norms=np.linalg.norm(arr)
print(norms)

[[1 2]
 [3 4]]

5.477225575051661
