In [2]:
import numpy as np
arr=np.array([[1,2],[3,4]])
print(arr)

[[1 2]
 [3 4]]


In [3]:
np.save('file.npy',arr)

In [4]:
loadedfile=np.load('file.npy')
print(loadedfile)

[[1 2]
 [3 4]]


In [5]:
np.savetxt('arr.txt',arr)

In [7]:
load=np.loadtxt('arr.txt')
print(load)

[[1. 2.]
 [3. 4.]]


In [9]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[10,20],[30,40]])
arr3=np.array([[11,21],[31,41]])
arr4=np.array([[12,22],[32,42]])

np.savez('fullfile',arr1,arr2,arr3,arr4)

In [16]:
arrs=np.load('fullfile.npz')
print(arrs)
for keys in arrs:
    print(arrs[keys])
    print()

NpzFile 'fullfile.npz' with keys: arr_0, arr_1, arr_2, arr_3
[[1 2]
 [3 4]]

[[10 20]
 [30 40]]

[[11 21]
 [31 41]]

[[12 22]
 [32 42]]



In [17]:
np.savez_compressed('compression',arr1,arr2)

In [18]:
arrs=np.load('compression.npz')
print(arrs)

for key in arrs:
    print(arrs[key])
    print()

NpzFile 'compression.npz' with keys: arr_0, arr_1
[[1 2]
 [3 4]]

[[10 20]
 [30 40]]

