In [2]:
import numpy as np


arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [7]:
zarr=np.zeros((3,3))
print(zarr)

oarr=np.ones((2,2))
print()
print(oarr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1.]
 [1. 1.]]


In [8]:
steparr=np.arange(0,10,2)
print(steparr)

[0 2 4 6 8]


In [12]:
ranarr=np.random.rand(3,3)
print(ranarr) # randome values from 0 to 1

[[0.58409074 0.22453449 0.55235714]
 [0.62719952 0.89313041 0.7291422 ]
 [0.89084831 0.48939526 0.07853472]]


In [15]:
eyarr=np.eye(2)
print(eyarr)
eyarr=np.eye(3)
print()
print(eyarr)
eyarr=np.eye(4)
print()
print(eyarr)

[[1. 0.]
 [0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
fullarr=np.full((2,2),6)
print(fullarr)
print()
fullarr=np.full((2,2),20)
print(fullarr)
print()
fullarr=np.full((2,2),'s')
print(fullarr)
print()

[[6 6]
 [6 6]]

[[20 20]
 [20 20]]

[['s' 's']
 ['s' 's']]



In [18]:
equalpart=np.linspace(0,10,5)
print(equalpart)

[ 0.   2.5  5.   7.5 10. ]
