In [6]:
import numpy as np

arr=np.array([1,2,3,4,5,6])
print(arr)
rearr=arr.reshape(3,2)
print()
print(rearr)

[1 2 3 4 5 6]

[[1 2]
 [3 4]
 [5 6]]


In [21]:
arr=np.array([[1,2],[3,5],[5,6]])
print(arr)
flatarr=arr.flatten()
print()
print(flatarr)
print()
arr=np.array([[[1,2,3],[2,3,4]],[[3,4,5],[3,4,6]]])
flarr=arr.flatten()
print(flarr)

[[1 2]
 [3 5]
 [5 6]]

[1 2 3 5 5 6]

[1 2 3 2 3 4 3 4 5 3 4 6]


In [42]:
arr1=np.array([1,2])
arr2=np.array([3,4])
print(arr1)
print()
print(arr2)

arr3=np.concatenate([arr1,arr2],axis=0)
print()
print(arr3)


arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6],[40,40]])

print()
print(arr1)
print()
print(arr2)
canarr3=np.concatenate([arr1,arr2],axis=0)
print()
print(canarr3)

canarr3=np.concatenate([arr1,arr2],axis=1)
print()
print(canarr3)
print()



[1 2]

[3 4]

[1 2 3 4]

[[1 2]
 [3 4]]

[[ 5  6]
 [40 40]]

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [40 40]]

[[ 1  2  5  6]
 [ 3  4 40 40]]



In [43]:
arr = np.array([[1, 2], [3, 4]])
print(arr.T)

[[1 3]
 [2 4]]


In [47]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr=np.vstack([arr1,arr2])
print(arr)
print()
arr=np.hstack([arr1,arr2])
print(arr)

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]


In [54]:
arr = np.array([1, 2, 3])
print(arr)
print()
arr=np.expand_dims(arr,axis=0)
print(arr)
print()
arr=np.expand_dims(arr,axis=1)
print(arr)
print()
arr=np.expand_dims(arr,axis=2)
print(arr)
print()
arr=np.expand_dims(arr,axis=3)
print(arr)

[1 2 3]

[[1 2 3]]

[[[1 2 3]]]

[[[[1 2 3]]]]

[[[[[1 2 3]]]]]


In [64]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print()
print(arr)
swapped=arr.swapaxes(0,1)
print()
print(swapped)


[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]
