In [4]:
import numpy as np
# an array with 4 rows and 3 columns
PyArr = np.empty([4,3], dtype = int)
print (PyArr)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [5]:
import numpy as np
# an array with 4 rows and 3 columns
PyArr = np.empty([4,3], dtype = str)
print (PyArr)

[['' '' '']
 ['' '' '']
 ['' '' '']
 ['' '' '']]


In [6]:
import numpy as np
PyArr = np.zeros ((3,3), dtype = int)
print(PyArr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
import numpy as np
PyArr = np.zeros((3,3), dtype = str)
print(PyArr)

[['' '' '']
 ['' '' '']
 ['' '' '']]


In [9]:
import numpy as np
PyArr = np.ones((3,3), dtype = str)
print(PyArr)

[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]


In [10]:
import numpy as np
PyArr = np.ones((3,3), dtype = int)
print(PyArr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [12]:
import numpy as np
PyArr = np.ones((3,3,3,3), dtype = str)
print(PyArr)

[[[['1' '1' '1']
   ['1' '1' '1']
   ['1' '1' '1']]

  [['1' '1' '1']
   ['1' '1' '1']
   ['1' '1' '1']]

  [['1' '1' '1']
   ['1' '1' '1']
   ['1' '1' '1']]]


 [[['1' '1' '1']
   ['1' '1' '1']
   ['1' '1' '1']]

  [['1' '1' '1']
   ['1' '1' '1']
   ['1' '1' '1']]

  [['1' '1' '1']
   ['1' '1' '1']
   ['1' '1' '1']]]


 [[['1' '1' '1']
   ['1' '1' '1']
   ['1' '1' '1']]

  [['1' '1' '1']
   ['1' '1' '1']
   ['1' '1' '1']]

  [['1' '1' '1']
   ['1' '1' '1']
   ['1' '1' '1']]]]


In [19]:
import numpy as np
PyArr = np.full([2, 2], 67, dtype = int)
print("\nMatrix a : \n\n", PyArr)
PyArr = np.full([3, 3], 10.1)
print("\nMatrix c : \n", PyArr)


Matrix a : 

 [[67 67]
 [67 67]]

Matrix c : 
 [[10.1 10.1 10.1]
 [10.1 10.1 10.1]
 [10.1 10.1 10.1]]


In [24]:
import numpy as np
pyarr=np.array([1,2,3,4],dtype=complex)
print(pyarr)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [39]:
import numpy as np
pyarr=np.array([1,2,3,4],dtype='i1')
print(pyarr)

# | Code | Meaning          |
# | `i`  | signed integer   |
# | `u`  | unsigned integer |
# | `f`  | float            |

# | dtype | Bytes | Bits |
# | `i1`  | 1     | 8    |
# | `i2`  | 2     | 16   |
# | `i4`  | 4     | 32   |
# | `i8`  | 8     | 64   |


[1 2 3 4]


In [43]:
import numpy as np
pyarr=np.array([1,2,3,4],dtype='U')
print(pyarr)

['1' '2' '3' '4']


In [56]:
import numpy as np
pyarr=np.array([1,2,3,4],dtype='S')
print(pyarr)
print(pyarr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [52]:
import numpy as np
a = np.array([120, 127, 130], dtype=np.int8)
print(a)
print(a.dtype)
# overfloe error is because we used np.int8 = 'i1'=1byte memory =8bits its rang from -128  to  +127

OverflowError: Python integer 130 out of bounds for int8

In [51]:
import numpy as np
a = np.array([120, 127, 130], dtype=np.int16)
print(a)
print(a.dtype)
# Here I increased memory from np.int8 to np.int16 so it its executed.

[120 127 130]
int16


In [ ]:
import numpy as np
narr=np.array([1,2,3,4,5],dtype=complex)
print(narr)
print(narr.dtype)
print(narr.itemsize)
print(narr.nbytes)

# i+j --> 'i' takes 8bytes , 'j' takes 8bytes ==> total =16bytes
# [1,2,3,4,5] --> 5*16bytes=80bytes memory for 5 numbers.


[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]
complex128
16
80


In [50]:
import numpy as np
pyarr=np.array(1)
print(pyarr)
print(pyarr.dtype)

1
int64


In [65]:
import numpy as np
aarr=np.array(['a','b'])
aarr.dtype

dtype('<U1')

In [66]:
import numpy as np
aarr=np.array(['ae','b'])
aarr.dtype

dtype('<U2')

In [77]:
import numpy as np
a = np.array([120, 127, 130], dtype=np.int8)
print(a)
print(a.dtype)
# overfloe error is because we used np.int8 = 'i1'=1byte memory =8bits its rang from -128  to  +127

OverflowError: Python integer 130 out of bounds for int8

In [67]:
import numpy as np
aarr=np.array(['a1111','b'])
aarr.dtype

dtype('<U5')

In [70]:
import numpy as np
nparray=np.array([1,2,3,4])
print(nparray)
print(nparray/2)

[1 2 3 4]
[0.5 1.  1.5 2. ]


In [75]:
pylist=[1,2,3,4]
print(pylist)
print(pylist/2) # which is not possible in list but in numpy can be possible


[1, 2, 3, 4]


TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [78]:
import numpy as np
print(dir(np))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__array_namespace_info__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_array_api_info', '_core', '_distributor_init', '_expired_attrs_2_0', '_globals', '_int_extended_msg', '_mat', '_msg', '_pyinstaller_hooks_dir', '_pytesttester', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'array_repr', 'array_split'

In [ ]:
import numpy as np
PyArr=np.array([2,4,5,6,7,8])
print(help(np.array))


Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``o

In [84]:
import numpy as np
PyArr=np.array([1,2,3,4])
print(type(PyArr))#<class 'numpy.ndarray'>
print(PyArr)#[1 2 3 4]
print(PyArr.dtype)

<class 'numpy.ndarray'>
[1 2 3 4]
int64


In [103]:
# 0-D array
darray=np.array(22)
print(darray)
print(darray.ndim)


22
0


In [134]:
# 1-D Array
import numpy as np
nparr=np.array((1,2,3))# or nparr=np.array([1,2,3])

print(nparr)
print(nparr.dtype)
print(nparr.ndim)

#2-D arrays
import numpy as np

arr2d=np.array(((1,2,3),(4,5,6)))
print(arr2d)
print(arr2d.ndim)


[1 2 3]
int64
1
[[1 2 3]
 [4 5 6]]
2


In [105]:
#2-D arrays
import numpy as np

arr2d=np.array([[1,2,3],[4,5,6]])
print(arr2d)
print(arr2d.ndim)

[[1 2 3]
 [4 5 6]]
2


In [97]:
# 3d array
array_3d=np.array([
    [[1,2,3]],
    [[4,5,6]],
    [[7,8,9]]
    ])
print(array_3d)
print(array_3d.ndim)

[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]
3


In [106]:
# 3-D array
array_3d=np.array([
    [[1,2,3],[1,1,1]],
    [[4,5,6],[2,2,2]],
    [[7,8,9],[3,3,3]]
    ])
print(array_3d)
print(array_3d.ndim)


[[[1 2 3]
  [1 1 1]]

 [[4 5 6]
  [2 2 2]]

 [[7 8 9]
  [3 3 3]]]
3


In [107]:
# Slicing 
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [108]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

[5 6 7]


In [109]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[1 2 3 4]


In [121]:
arr = np.array([1, 2, 3, 4, 5, 6, 7,8,9,10])
# print(arr[::0]) This comes error becsuse slicing starts from 1
print("Slicing 1 ",arr[::1])
print("Slicing 2 ",arr[::2])
print("Slicing 3 ",arr[::3])
print("Slicing 4 ",arr[::4])
print("Slicing 5 ",arr[::5])
print("Slicing 6 ",arr[::6])

Slicing 1  [ 1  2  3  4  5  6  7  8  9 10]
Slicing 2  [1 3 5 7 9]
Slicing 3  [ 1  4  7 10]
Slicing 4  [1 5 9]
Slicing 5  [1 6]
Slicing 6  [1 7]


In [123]:
# Data types in numpy
import numpy as np
PyArr = np.array([1, 2, 3, 4])
print(PyArr.dtype) 

int64


In [124]:
import numpy as np
PyArr = np.array(['1', '2', '3', '4'])
print(PyArr.dtype) #<U1


<U1


In [125]:
import numpy as np
PyArr = np.array(['11', '21', '13', '14'])
print(PyArr.dtype) #<U2

<U2


In [126]:
import numpy as np
PyArr = np.array(['Data', 'BigData', 'Hadoop'])
print(PyArr.dtype) #U7(7 bytes)

<U7


In [135]:
import numpy as np
PyArr = np.array([(1,2,3)])
print(PyArr.dtype)
print(PyArr.ndim)


int64
2


In [136]:
import numpy as np
PyArr = np.array([1,2,3,4,5])
print(PyArr.size)

5


In [ ]:
# dtype='i' it convert the array into "integer"
nparr = np.array([1,2,3,4,5],dtype='i')
print(nparr)

# dtype='S' it convert the array into 'string'
nparr = np.array([1,2,3,4,5],dtype='S')
print("Here 'b' represents bytes string : ",nparr)
# NOTE: For i, u, f, S and U we can define size as well. Here 'b' represents bytes string.

# dtype='U' it convert the array into "unicode string"
nparr = np.array([1,2,3,4,5],dtype='U')
print(nparr)

# dtype='U' it convert the array into "complex float"
nparr = np.array([1,2,3,4,5],dtype=complex)
print(nparr)


[1 2 3 4 5]
Here 'b' represents bytes string :  [b'1' b'2' b'3' b'4' b'5']
['1' '2' '3' '4' '5']
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


In [152]:
# dtype='i4' it convert the array into "4 byte integer"
PyArr = np.array([1, 2, 3, 4], dtype='i4')
print(PyArr)
print(PyArr.dtype) 


[1 2 3 4]
int32


In [154]:
import numpy as np
nparr=np.array([1,2,3,4,'a'],dtype='i') # Can't convert non interger string to int ex here : 'a'
print(nparr)

ValueError: invalid literal for int() with base 10: 'a'

In [169]:
# Converting Data Type on Existing Arrays
npar=np.array([1,2.3,4,6])
print("array float : ",npar)
print(npar.dtype)

# conveting float to int
intar=npar.astype('i') # 
print("converted to int : ",intar)
print(intar.dtype)
print("Older array type will not change : ",npar.dtype)

# conveting float to str
strar=npar.astype('S')
print("Converted to string and its a byte string that why 'b' is there : ",strar)
print(strar.dtype)

# conveting float to bool
exarr=np.array([0,1,-1,1.2])
barr=exarr.astype(bool)
print("Bool array : ",barr)




array float :  [1.  2.3 4.  6. ]
float64
converted to int :  [1 2 4 6]
int32
Older array type will not change :  float64
Converted to string and its a byte string that why 'b' is there :  [b'1.0' b'2.3' b'4.0' b'6.0']
|S32
Bool array :  [False  True  True  True]


In [173]:
import numpy as np
PyArr = np.array([1,2,3,4])
print(PyArr.itemsize)



8


In [175]:
import numpy as np

onar = np.ones([2,2])
print(onar)

[[1. 1.]
 [1. 1.]]


In [178]:
farr=np.full([2,2],'d')
print(farr)

[['d' 'd']
 ['d' 'd']]
