In [1]:
import numpy as np
pyarr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(pyarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
pyarr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(pyarr[0:2,0:2])



[[1 2]
 [6 7]]
[[ 2  4]
 [12 14]]
