In [1]:
import numpy as np
pyarr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(pyarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [6]:
pyarr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(pyarr.ndim)
print(pyarr[0:2,0:2])



2
[[1 2]
 [6 7]]


In [11]:
pyarr=np.array([[[10,20,30],
                 [40,50,60]],
                
                [[70,80,90],
                 [100,110,120]]])

print(pyarr.ndim)
print(pyarr[0,1,0:2])
print(pyarr[1,1,2])
print(pyarr[1,1,0:2])

3
[40 50]
120
[100 110]


In [26]:
PyArr = np.array([[11, 28], [23, 84], [95, 56]]) 
MyArr = PyArr[[0,1,2], [0,0,1]] 
# 0,0
# 1,0
# 2,1
print(MyArr) 
print(PyArr[0])
print(PyArr[0,1])
print(PyArr[[0],[1]]+1)
PyArr[[0],[1]]+=1
print()
print(PyArr)


[11 23 56]
[11 28]
28
[29]

[[11 29]
 [23 84]
 [95 56]]


In [30]:

import numpy as np 
PyArr = np.array([[11, 51, 2],[23, 24, 5], [16, 47, 8] ,[91, 10, 11]]) 
print(PyArr[PyArr>5])
print(PyArr[PyArr>=30])
print(PyArr[PyArr>=47])

[11 51 23 24 16 47  8 91 10 11]
[51 47 91]
[51 47 91]
