In [2]:
# Example 1: Adding two 1-d Arrays of the same shape
import numpy as np
pyarr1=np.array([1,2,3,4])
pyarr2=np.array([2,7,8,9])
pyarr3=pyarr1+pyarr2
print(pyarr3)

[ 3  9 11 13]


In [3]:
pyarr1 = np.array([4,5,6,7])  
pyarr2 = np.array([1,3,5,7,9,11,14])  
pyarr3=pyarr1+pyarr2
print(pyarr3)

ValueError: operands could not be broadcast together with shapes (4,) (7,) 

In [10]:
pyarr1=np.array([[0],[10],[20],[30]])
pyarr2=np.array([0,1,2])
print(pyarr1+pyarr2)
print()
print(pyarr1-pyarr2)
print()
print(pyarr1*pyarr2)



[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]

[[ 0 -1 -2]
 [10  9  8]
 [20 19 18]
 [30 29 28]]

[[ 0  0  0]
 [ 0 10 20]
 [ 0 20 40]
 [ 0 30 60]]


In [23]:
pyarr= np.array([[5,2,7,4],[9,0,2,3],[1,2,3,19]])  
print(pyarr)
pyarr1=pyarr
print()
print(pyarr1)
print()
print(id(pyarr))
print(id(pyarr1))
pyarr1.shape=4,3
print()
print(pyarr)


[[ 5  2  7  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]

[[ 5  2  7  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]

4475101104
4475101104

[[ 5  2  7]
 [ 4  9  0]
 [ 2  3  1]
 [ 2  3 19]]


In [82]:
a1 = np.array([5, 4, 6, 8, 9])
print(a1)
a1copy=a1.copy()
print(a1copy)
print(id(a1))
print(id(a1copy))
a1copy[0]=100
print(a1copy)
print(a1)

[5 4 6 8 9]
[5 4 6 8 9]
4478018512
4478020048
[100   4   6   8   9]
[5 4 6 8 9]


In [83]:
b1 = np.array([2, 4, 6, 8, 10,12])
print(b1)
b1v=b1.view()
print(b1v)

print(id(b1))
print(id(b1v))

b1v[0]=20
print(b1v)
print(b1)



[ 2  4  6  8 10 12]
[ 2  4  6  8 10 12]
4478024176
4477397936
[20  4  6  8 10 12]
[20  4  6  8 10 12]


In [37]:
PyArr1 = np.arange(0,60,5) 
PyArr1 = PyArr1.reshape(3,4) 
print (PyArr1)
print ()

PyArr2 = np.array([1, 2, 3, 4], dtype = int) 
print (PyArr2)  
print ()

for x,y in np.nditer([PyArr1,PyArr2]): 
    print ("%d:%d" %(x,y))

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

[1 2 3 4]

0:1
5:2
10:3
15:4
20:1
25:2
30:3
35:4
40:1
45:2
50:3
55:4


In [73]:
pyarr=np.arange(0,50,6)
print(pyarr)
pyarr=pyarr.reshape(3,3)
print(pyarr)
print()

for item in np.nditer(pyarr,op_flags=['readwrite']):
    item+=2
print(pyarr)
print()
for item in np.nditer(pyarr,op_flags=['readwrite']):
    # item[...]=2+item
    print(item[...] , item)
    print(type(item))
    print(type(item[...]))

# print(pyarr)

# for item in np.nditer(pyarr): # Error
#     item+=2
# print(pyarr)
    

[ 0  6 12 18 24 30 36 42 48]
[[ 0  6 12]
 [18 24 30]
 [36 42 48]]

[[ 2  8 14]
 [20 26 32]
 [38 44 50]]

2 2
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
8 8
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
14 14
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
20 20
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
26 26
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
32 32
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
38 38
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
44 44
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
50 50
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [61]:
pyarr1 = np.array([[11,2,23],[14,75,6],[17,8,9]], ndmin=3)
print(pyarr1)
pyarr2 = np.array([[9,8,7],[6,5,4],[3,2,1]], ndmin=3) 
print()
print(pyarr2)

pyarr3=np.multiply(pyarr1,pyarr2)

print()
print(pyarr3)


[[[11  2 23]
  [14 75  6]
  [17  8  9]]]

[[[9 8 7]
  [6 5 4]
  [3 2 1]]]

[[[ 99  16 161]
  [ 84 375  24]
  [ 51  16   9]]]


In [66]:
pyarrr1 = np.array([[1,2,3], [4,5,6],[1,2,1]])
print(pyarrr1)
pyarrr2 = np.array([[1,1,1], [0,1,0], [1,1,1]])
print()
print(pyarrr2)
pyarrr3=np.matmul(pyarrr1,pyarrr2)
print()
print(pyarrr3)



[[1 2 3]
 [4 5 6]
 [1 2 1]]

[[1 1 1]
 [0 1 0]
 [1 1 1]]

[[ 4  6  4]
 [10 15 10]
 [ 2  4  2]]


In [76]:
import numpy as np
pyarr1 = np.array([7,9,8])
pyarr2 = np.array([2,5,6])
print(pyarr1)
print(pyarr2)
pyarr3=np.dot(pyarr1,pyarr2)
print(pyarr3)

[7 9 8]
[2 5 6]
107


In [78]:
pyarr1 = np.array([[1,4],[3,1]])
pyarr2 = np.array([[4,5],[6,5]])
print(pyarr1)
print()
print(pyarr1)
print()
pyarr3=np.dot(pyarr1,pyarr2)
print(pyarr3)

[[1 4]
 [3 1]]

[[1 4]
 [3 1]]

[[28 25]
 [18 20]]


In [80]:
p1 = np.array([[1,4],[3,1]])
p2 = np.array([[4,5],[6,5]])

p5=np.matmul(p1,p2)
print(p5)

[[28 25]
 [18 20]]


In [81]:
m1 = np.array([[1,4],[3,1]])
m2 = np.array([[4,5],[6,5]])

m5=np.matmul(m1,m2)
print(m5)

[[28 25]
 [18 20]]


In [84]:
import numpy as np  
PyArr1 = np.array([[1, 2, 3], [7, 8, 9]])  
PyArr2 = np.array([[11, 21, 31], [42, 52, 62]])  
print(PyArr1)
print(PyArr2)
PyArr3 = np.append(PyArr1,PyArr2)  
print(PyArr3)

[[1 2 3]
 [7 8 9]]
[[11 21 31]
 [42 52 62]]
[ 1  2  3  7  8  9 11 21 31 42 52 62]


In [87]:
PyArr1 = np.array([[1, 2, 3], [7, 8, 9]])  
PyArr2 = np.array([[11, 21, 31], [42, 52, 62]])  
print(PyArr1)
print()
print(PyArr2)
print()
PyArr3 = np.append(PyArr1,PyArr2,axis=0)  
print(PyArr3)
print()
PyArr4 = np.append(PyArr1,PyArr2,axis=1)  
print(PyArr4)

[[1 2 3]
 [7 8 9]]

[[11 21 31]
 [42 52 62]]

[[ 1  2  3]
 [ 7  8  9]
 [11 21 31]
 [42 52 62]]

[[ 1  2  3 11 21 31]
 [ 7  8  9 42 52 62]]
