In [1]:
import numpy as np

nparr=np.array([1,2,3,4])

coarr=nparr.copy()
coarr[0]=100
print("Numpy arr : ",nparr)
print("Copy arr : ",coarr)

Numpy arr :  [1 2 3 4]
Copy arr :  [100   2   3   4]


In [4]:
import numpy as np

nparr=np.array([1,2,3,4])

coarr=nparr.copy()
coarr[0]=100
print("Numpy arr : ",nparr)
print("Copy arr : ",coarr)

Numpy arr :  [1 2 3 4]
Copy arr :  [100   2   3   4]


In [10]:
import numpy as np

originalarr=np.array([1,2,3,4,5])

viewarr=originalarr.view()
viewarr[0]=100
print("original arr : ",originalarr)
print("view arr : ",viewarr)

original arr :  [100   2   3   4   5]
view arr :  [100   2   3   4   5]


In [12]:
import numpy as np

originalarr=np.array([1,2,3,4,5])

viewarr=originalarr.view()
originalarr[0]=1000
print("original arr : ",originalarr)
print("view arr : ",viewarr)

original arr :  [1000    2    3    4    5]
view arr :  [1000    2    3    4    5]


In [13]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31
print(arr)
print(x)


[31  2  3  4  5]
[31  2  3  4  5]


In [14]:
import numpy as np

arr=np.array([1,2,3,4,5])
x=arr.copy()
y=arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [15]:
# Python NumPy Array Creation using existing data
# Numpy library provides various ways to create an array from the existing data:

import numpy as np

list=[10,20,30,40]
res=np.asarray(list,dtype=float)
print(res)

[10. 20. 30. 40.]


In [16]:

import numpy as np

list=[10,20,30,40]
res=np.asarray(list,dtype=int)
print(res)

[10 20 30 40]


In [17]:

import numpy as np

list=[10,20,30,40]
res=np.asarray(list,dtype=str)
print(res)

['10' '20' '30' '40']


In [21]:

import numpy as np

list=[10,20,30,40,50]
res=np.asarray(list,dtype=str,order='C')
print(res)

['10' '20' '30' '40' '50']


In [ ]:
import numpy as np  
PyList1=[[10,20,30],[40,50,60]]
print(PyList1)
print()
PyResult=np.asarray(PyList1,dtype=int,order='F')
print(PyResult)


[[10, 20, 30], [40, 50, 60]]

[[10 20 30]
 [40 50 60]]


In [34]:
pyarr=np.arange(0,40,5)
print(pyarr)
for items in np.nditer(pyarr):
    print(items)

[ 0  5 10 15 20 25 30 35]
0
5
10
15
20
25
30
35


In [46]:
f=np.array([[1,2,3,4],[5,6,7,8],[10,20,30,40]])
g=np.nditer(f)
for item in g:
    print(item)

1
2
3
4
5
6
7
8
10
20
30
40


In [50]:
import numpy as np
PyArr = np.arange(0,40,5)
pyarr=np.array([1,2,3])

print(type(PyArr))
print(type(pyarr))
print()
print (PyArr)
for item in np.nditer(PyArr):
    print(item)


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

[ 0  5 10 15 20 25 30 35]
0
5
10
15
20
25
30
35


In [51]:
nparr=np.arange(0,10,2,'complex')
for item in np.nditer(nparr):
    print(item)


0j
(2+0j)
(4+0j)
(6+0j)
(8+0j)


In [ ]:
# Convert list to numpy array

import numpy as np
list=[1,2,3,4,5]
nparr=np.asarray(list)
print(list)
print(type(list))

print()

print(nparr)
print(type(nparr))



[1, 2, 3, 4, 5]
<class 'list'>

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
pylist=[[1,2,3,4],[5,6,7,8]]
print(type(pylist))
print()
nparr=np.asarray(pylist,dtype=int)
print(nparr)
print(type(nparr))

print()

nparr=np.asarray(pylist,dtype=str)
print(nparr)
print(type(nparr))

print()

nparr=np.asarray(pylist,dtype=float)
print(nparr)
print(type(nparr))


<class 'list'>

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>

[['1' '2' '3' '4']
 ['5' '6' '7' '8']]
<class 'numpy.ndarray'>

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
<class 'numpy.ndarray'>


In [ ]:
pylist=[[1,2,3,4],[5,6,7,8]]
print(pylist)
print(type(pylist))
print()
nparr=np.asarray(pylist,dtype=int,order='C') # 'C' ==> Row major order
print(nparr)
print(type(nparr))
print()

for item in np.nditer(nparr):
    print(item)



[[1, 2, 3, 4], [5, 6, 7, 8]]
<class 'list'>

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>

1
2
3
4
5
6
7
8


In [126]:
# pylist=[[1,2,3,4],[5,6,7,8]]
pylist=[['1','2'],['3','4']]
print(pylist)
print(type(pylist))
print()
nparr=np.asarray(pylist,dtype=int,order='F') # 'F' ==> Column major order
print(nparr)
print(type(nparr))
print()

for item in np.nditer(nparr):
    print(item)



[['1', '2'], ['3', '4']]
<class 'list'>

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>

1
3
2
4


In [93]:
import numpy as np  
# intialize bytes
p='PYTHON' # Conveting a normal string to byte string
print("Normal string ", p)
print("Type of Normal string ", type(p))

pyStr=p.encode('utf-8') 
    # (or)
#pyStr=b'PYTHON' #b is prefix, it saved in terms of bytes(ASCII) not in string format.
print("\nConverted a normal string to byte string : ", pyStr)
print("Type of byte string ", type(pyStr))

# Below line Converting byte str to nparray
bydata=np.frombuffer(pyStr,"S1")  #S1 means 1 byte data
print(f"\n Converted a byte string to numpy array : {bydata}")
print(f" Type of numpy array : {type(bydata)}")

Normal string  PYTHON
Type of Normal string  <class 'str'>

Converted a normal string to byte string :  b'PYTHON'
Type of byte string  <class 'bytes'>

 Converted a byte string to numpy array : [b'P' b'Y' b'T' b'H' b'O' b'N']
 Type of numpy array : <class 'numpy.ndarray'>


In [ ]:
bydata=np.frombuffer(pyStr,"S2")  #S2 means 1 byte data
print(f"\n Converted a byte string to numpy array : {bydata}")
print(f" Type of numpy array : {type(bydata)}")


 Converted a byte string to numpy array : [b'PY' b'TH' b'ON']
 Type of numpy array : <class 'numpy.ndarray'>


In [ ]:
bydata=np.frombuffer(pyStr,"S3")  #S3 means 1 byte data
print(f"\n Converted a byte string to numpy array : {bydata}")
print(f" Type of numpy array : {type(bydata)}")


 Converted a byte string to numpy array : [b'PYT' b'HON']
 Type of numpy array : <class 'numpy.ndarray'>


In [ ]:
bydata=np.frombuffer(pyStr,"S4")  #S4 means 1 byte data
print(f"\n Converted a byte string to numpy array : {bydata}")
print(f" Type of numpy array : {type(bydata)}")

ValueError: buffer size must be a multiple of element size

In [ ]:
bydata=np.frombuffer(pyStr,"S1",count=-1,offset=1)
print(f"\n Converted a byte string to numpy array : {bydata}")
print(f" Type of numpy array : {type(bydata)}")


 Converted a byte string to numpy array : [b'Y' b'T' b'H' b'O' b'N']
 Type of numpy array : <class 'numpy.ndarray'>


In [ ]:
bydata=np.frombuffer(pyStr,"S1",count=-1,offset=4) 
print(f"\n Converted a byte string to numpy array : {bydata}")
print(f" Type of numpy array : {type(bydata)}")


 Converted a byte string to numpy array : [b'O' b'N']
 Type of numpy array : <class 'numpy.ndarray'>


In [116]:
print(pyStr)
bydata=np.frombuffer(pyStr,"S1",count=1,offset=2)  # count is from which index should I be print
    # offset ==> how many skips in the letters
print(f"\n Converted a byte string to numpy array : {bydata}")
print(f" Type of numpy array : {type(bydata)}")

b'PYTHON'

 Converted a byte string to numpy array : [b'T']
 Type of numpy array : <class 'numpy.ndarray'>


In [118]:
print(pyStr)
bydata=np.frombuffer(pyStr,"S1",count=2,offset=1)
print(bydata)

b'PYTHON'
[b'Y' b'T']


In [125]:
# Syntax:
# numpy.fromiter(iterable, dtype, count)
# 1. iterable ==> list or tuple
# 2. dtype ==> int, float,,str
# 3. count ==> Length of returned array, default -1


pyTuple=(1,2,3,4)
print(pyTuple)
print(type(pyTuple))
iteration=iter(pyTuple)
print(iteration)
pyFor=np.fromiter(iteration,dtype=float)
print(pyFor)
print(type(pyFor))

(1, 2, 3, 4)
<class 'tuple'>
[1. 2. 3. 4.]
<class 'numpy.ndarray'>


In [128]:
np.fromiter(iteration,dtype=int,count=1)

ValueError: iterator too short: Expected 1 but iterator had only 0 items.

In [129]:
import numpy as np  
PyTuple = (2,4,6,20)  
Iter = iter(PyTuple)  
PyFor = np.fromiter(Iter, dtype = int,count=-1)  
print(PyFor)  
print(type(PyFor)) 

[ 2  4  6 20]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np  
PyTuple = (2,4,6,20)  
Iter = iter(PyTuple)  
PyFor = np.fromiter(Iter,int,count=2)  
print(PyFor)  
print(type(PyFor))

[2 4]
<class 'numpy.ndarray'>


In [131]:
# Python NumPy Array Creation from Numerical Ranges
# The Numpy library provides some functions to create an array from the given specified range. 
# 1    numpy.arange
# 2    numpy.linspace
# 3    numpy.logspace


In [133]:
pyarr=np.arange(10)
print(pyarr)

[0 1 2 3 4 5 6 7 8 9]


In [137]:
pyarr=np.arange(0,7,2,'complex')
print(pyarr)

[0.+0.j 2.+0.j 4.+0.j 6.+0.j]


In [138]:
# 2. Using numpy.linspace
# It is similar to the arange() function. But there is a major difference and it is in this function, instead of step size, the number of evenly spaced values between the interval is specified using the num argument.

# Syntax:
# numpy.linspace(start, stop, num,endpoint, retstep,dtype)   

# start    => start of interval range. 
# stop     =>  end of interval range
# num      => [int, optional] No. of samples to generate, Default 50
# endpoint => If True, stop index is included, If False Not Included. Default, True
# ReturnStep   => It returns the difference between values. True-Visible, False-NotVisible(Default)
# dtype    => type of output array

In [144]:
pyarr=np.linspace(0,10,4)
print(pyarr)

[ 0.          3.33333333  6.66666667 10.        ]


In [145]:
PyArr = np.linspace(0, 10, 5)  
print(PyArr)
PyArr = np.linspace(0, 10, 3)  
print(PyArr)
PyArr = np.linspace(10, 20, 3,endpoint=False)  #EndIndexNotIncluded
print(PyArr)
PyArr = np.linspace(0, 10, 5,endpoint=False,retstep=True)  
print(PyArr)
PyArr = np.linspace(0, 10, 5,endpoint=False,retstep=True,dtype=int)  
print(PyArr)


[ 0.   2.5  5.   7.5 10. ]
[ 0.  5. 10.]
[10.         13.33333333 16.66666667]
(array([0., 2., 4., 6., 8.]), np.float64(2.0))
(array([0, 2, 4, 6, 8]), np.float64(2.0))


In [147]:

# 3. Using numpy.logspace
# It is used to create an array by using the numbers that are evenly separated on a log scale.

# Syntax:
# numpy.logspace(start, stop, num, endpoint, base, dtype) 
# start    => start of interval range. 
# stop     =>  end of interval range
# num      => [int, optional] No. of samples to generate, Default 50
# endpoint => If True, stop index is included, If False Not Included.Default, True
# base     => [float, optional] Base of log scale. Default-10.0
# dtype    => type of output array


In [151]:
PyData = np.logspace(0, 10, num = 6, endpoint = True)  
print(PyData)

[1.e+00 1.e+02 1.e+04 1.e+06 1.e+08 1.e+10]


In [152]:
import numpy as np
PyArr = np.array([1,2,3,4,5])
print(PyArr.shape)

(5,)


In [154]:
import numpy as np
PyArr = np.array(([1,2,3,4,5],[6,7,8,9,10]))
print(PyArr)
print(PyArr.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [159]:
pyarr = np.array([[8,9,10],(11,12,13)])
print(pyarr)
print(pyarr.shape)
d=pyarr.reshape(3,2)
print(d)
print(d.shape)


[[ 8  9 10]
 [11 12 13]]
(2, 3)
[[ 8  9]
 [10 11]
 [12 13]]
(3, 2)


In [160]:
# Reshape From 1-D to 2-D
import numpy as np
PyArr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
NewArr = PyArr.reshape(4, 3)
print(NewArr) 


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [161]:
# Reshape From 1-D to 3-D

import numpy as np
PyArr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
NewArr = PyArr.reshape(2, 3, 2)
print(NewArr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [162]:
import numpy as np  
PyArr1 = np.arange(12)  
print(PyArr1)
print()
PyArr2 = np.reshape(PyArr1, (4, 3), order='F')  
print(PyArr2)
print()
PyArr3 = np.reshape(PyArr1, (4, 3), order='C')  
print(PyArr3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [164]:
# eye() function
# It is used to create a 2-D array with ones on the diagonal and zeros elsewhere.
# take square matrix, initialize 1's on all diagonal positions, 0's on all Non-diagonal positions.

# Syntax:
# numpy.eye(N, M=None, k=0, dtype='float')

# N	Number of rows in the output.			
# M	Number of columns in the output. If None, defaults to N.	
# k	Index of the diagonal: 0
# dtype	Data-type of the returned array.

In [165]:
import numpy as np
print(np.eye(2))
print(np.eye(3,3))
print(np.eye(3,3,dtype=int))

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [190]:
import numpy as np
print(np.eye(2,k=-1))
print(np.eye(2,2,k=-1))
print(np.eye(3,3,k=-2))
# print(np.eye(3,3,k=2))

[[0. 0.]
 [1. 0.]]
[[0. 0.]
 [1. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]]
