In [2]:
import numpy as np

arr=np.array([1,2,3])
for item in arr:
    print(item)

1
2
3


In [5]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6]])
for item in arr:
    for data in item:
        print(data)

1
2
3
4
5
6


In [6]:
import numpy as np
PyArr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for data in PyArr:
  print(data) 


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [7]:
import numpy as np
PyArr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for data in PyArr:
  for pdata in data:
    for qdata in pdata:
      print(qdata) 

1
2
3
4
5
6
7
8
9
10
11
12


In [8]:
# Iterating Arrays Using nditer()
# It is a helping function that can be used from very basic to very advanced iterations.

# Syntax:
# numpy.nditer(sequence/ndarray)

# Iterating on Each Scalar Element
# In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.


In [10]:
pyArr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for item in np.nditer(pyArr):
    print(item)

1
2
3
4
5
6
7
8
9
10
11
12


In [11]:
# Enumerated Iteration Using ndenumerate()
# Enumeration means mentioning sequence number of somethings one by one.


for index,value in np.ndenumerate(pyArr):
    print(f"index : {index} and value : {value}")

index : (0, 0, 0) and value : 1
index : (0, 0, 1) and value : 2
index : (0, 0, 2) and value : 3
index : (0, 1, 0) and value : 4
index : (0, 1, 1) and value : 5
index : (0, 1, 2) and value : 6
index : (1, 0, 0) and value : 7
index : (1, 0, 1) and value : 8
index : (1, 0, 2) and value : 9
index : (1, 1, 0) and value : 10
index : (1, 1, 1) and value : 11
index : (1, 1, 2) and value : 12


In [17]:
# NumPy Joining Array
# NumPy concatenate() Method:
# It is mainly used in order to combine two or more NumPy arrays together. 
# Concatenation of two numpy arrays simply means their stacking. it is taken default as 0.

pyarr1=np.array([1,2,3])
pyarr2=np.array([4,5,6])
pyarr3=np.concatenate((pyarr1,pyarr2))
print(pyarr3)

[1 2 3 4 5 6]


In [30]:

pyarr1=np.array([[1,2,3],[4,5,6]])
pyarr2=np.array([[7,8,9],[10,11,12]])
print(pyarr1)
print(pyarr2)
pyarr4=np.concatenate((pyarr1,pyarr2),axis=1)
print()
print(pyarr4)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [25]:
# Example: axis-1->Rows
pyarr1=np.array([[1,2,3],[4,5,6]])
pyarr2=np.array([[7,8,9],[10,11,12]])
print(pyarr1)
print(pyarr2)
pyarr4=np.concatenate((pyarr1,pyarr2),axis=1)
print(pyarr4)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [26]:
# Example: axis-0->Col
pyarr1=np.array([[1,2,3],[4,5,6]])
pyarr2=np.array([[7,8,9],[10,11,12]])
print(pyarr1)
print(pyarr2)
pyarr4=np.concatenate((pyarr1,pyarr2),axis=0)
print(pyarr4)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [32]:
pyarr1=np.arange(6).reshape(2,3)
pyarr2=np.arange(7,13).reshape(2,3)
print(pyarr1)
print(pyarr2)
print()
pyarr3=np.concatenate((pyarr1,pyarr2))
print(pyarr3)

[[0 1 2]
 [3 4 5]]
[[ 7  8  9]
 [10 11 12]]

[[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]]


In [33]:
pyarr1=np.arange(6).reshape(2,3)
pyarr2=np.arange(7,13).reshape(2,3)
print(pyarr1)
print(pyarr2)
print()
pyarr3=np.concatenate((pyarr1,pyarr2),axis=1)
print(pyarr3)

[[0 1 2]
 [3 4 5]]
[[ 7  8  9]
 [10 11 12]]

[[ 0  1  2  7  8  9]
 [ 3  4  5 10 11 12]]


In [34]:
# Joining Arrays Using Stack Functions
# Stacking is same as concatenation, the only difference is that stacking is done along a new axis. Result is in two different dimensions.
pyarr1=np.arange(6).reshape(2,3)
pyarr2=np.arange(7,13).reshape(2,3)
print(pyarr1)
print(pyarr2)
print()
pyarr3=np.stack((pyarr1,pyarr2))
print(pyarr3)


[[0 1 2]
 [3 4 5]]
[[ 7  8  9]
 [10 11 12]]

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 7  8  9]
  [10 11 12]]]


In [35]:
# Joining Arrays Using Stack Functions
# Stacking is same as concatenation, the only difference is that stacking is done along a new axis. Result is in two different dimensions.
pyarr1=np.arange(6).reshape(2,3)
pyarr2=np.arange(7,13).reshape(2,3)
print(pyarr1)
print(pyarr2)
print()
pyarr3=np.stack((pyarr1,pyarr2),axis=1)
print(pyarr3)


[[0 1 2]
 [3 4 5]]
[[ 7  8  9]
 [10 11 12]]

[[[ 0  1  2]
  [ 7  8  9]]

 [[ 3  4  5]
  [10 11 12]]]


In [ ]:

pyarr1=np.arange(6).reshape(2,3)
pyarr2=np.arange(7,13).reshape(2,3)
print(pyarr1)
print(pyarr2)
print()
pyarr3=np.concatenate((pyarr1,pyarr2),axis=1)
print(pyarr3)


[[0 1 2]
 [3 4 5]]
[[ 7  8  9]
 [10 11 12]]

[[ 0  1  2  7  8  9]
 [ 3  4  5 10 11 12]]


In [41]:
# Stacking Along Rows
# NumPy provides a helper function: hstack() to stack along rows.

import numpy as np
pyArr1=np.arange(6).reshape(2,3)
print(pyArr1)
print()
pyArr2=np.arange(7,13).reshape(2,3)
print(pyArr2)
print()
pyarr3=np.hstack((pyArr1,pyArr2))

print(pyarr3)
print()
print(np.concatenate((pyArr1,pyArr2),axis=1))

[[0 1 2]
 [3 4 5]]

[[ 7  8  9]
 [10 11 12]]

[[ 0  1  2  7  8  9]
 [ 3  4  5 10 11 12]]

[[ 0  1  2  7  8  9]
 [ 3  4  5 10 11 12]]


In [43]:
# Stacking Along Rows
# NumPy provides a helper function: hstack() to stack along rows.

import numpy as np
pyArr1=np.arange(6).reshape(2,3)
print(pyArr1)
print()
pyArr2=np.arange(7,13).reshape(2,3)
print(pyArr2)
print()
pyarr3=np.vstack((pyArr1,pyArr2))

print(pyarr3)
print()
print(np.concatenate((pyArr1,pyArr2),axis=0))

[[0 1 2]
 [3 4 5]]

[[ 7  8  9]
 [10 11 12]]

[[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]]

[[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]]


In [44]:

import numpy as np
pdata= np.array([(1,2,3),(3,4,5)])
qdata= np.array([(1,2,3),(3,4,5)])
print(np.vstack((pdata,qdata)))
print(np.hstack((pdata,qdata)))

[[1 2 3]
 [3 4 5]
 [1 2 3]
 [3 4 5]]
[[1 2 3 1 2 3]
 [3 4 5 3 4 5]]


In [46]:
# Stacking Along Height (depth)
# NumPy provides a helper function: dstack() to stack along height, which is the same as depth.

pyArr1=np.arange(6).reshape(2,3)
print(pyArr1)
print()
pyArr2=np.arange(7,13).reshape(2,3)
print(pyArr2)
print()
pyarr3=np.dstack((pyArr1,pyArr2))
print(pyarr3)

[[0 1 2]
 [3 4 5]]

[[ 7  8  9]
 [10 11 12]]

[[[ 0  7]
  [ 1  8]
  [ 2  9]]

 [[ 3 10]
  [ 4 11]
  [ 5 12]]]


In [51]:
arr1=np.array([1,2,3,4,5,6,7,8])
print(arr1)
arr2=np.split(arr1,2)
print(arr2)

[1 2 3 4 5 6 7 8]
[array([1, 2, 3, 4]), array([5, 6, 7, 8])]


In [52]:
arr1=np.array([1,2,3,4,5,6,7,8])
print(arr1)
arr2=np.split(arr1,3)
print(arr2)

[1 2 3 4 5 6 7 8]


ValueError: array split does not result in an equal division

In [57]:
import numpy as np
PyArr = np.array([[1, 2, 3, 4, 5, 6]])
NewArr = np.split(PyArr, 3,axis=1)
print(NewArr) 

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]


In [ ]:
import numpy as np
PyArr = np.array([1, 2, 3, 4, 5, 6])
NewArr = np.array_split(PyArr, 3) # It will not give you error for unequal split
print(NewArr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
import numpy as np
PyArr = np.array([1, 2, 3, 4, 5, 6])
NewArr = np.array_split(PyArr, 4) # It will not give you error for unequal split
print(NewArr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


array([1, 2])

In [65]:
# 2-D
pyarr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
pyarr1=np.array_split(pyarr,5)
print(pyarr1)

[array([[1, 2],
       [3, 4]]), array([[5, 6]]), array([[7, 8]]), array([[ 9, 10]]), array([[11, 12]])]


In [68]:
import numpy as np
PyArr = np.array([1, 2, 3, 4,5, 6,])
NewArr = np.hsplit(PyArr,3)
print(NewArr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [69]:
# vsplit() ==> This method is not applicable for single dimension. Minimum 2DArray required.

import numpy as np
PyArr = np.array([[1, 2, 3], [4,5, 6,]])
NewArr = np.vsplit(PyArr,2)
print(NewArr)


[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [76]:
pyarr=np.array([10,1,2,3,4,100,20])
print(np.where(pyarr==100))
print(np.where(pyarr==3))
print(np.where(pyarr%2==0))

(array([5]),)
(array([3]),)
(array([0, 2, 4, 5, 6]),)


In [77]:
import numpy as np
PyArr=np.arange(-10, -1)
print(PyArr)

[-10  -9  -8  -7  -6  -5  -4  -3  -2]


In [78]:
import numpy as np
PyArr=np.arange(10,100,10)
print(PyArr)
print(np.where(PyArr==40))
print(np.where(PyArr==60))
print(np.where(PyArr%30==0))

[10 20 30 40 50 60 70 80 90]
(array([3]),)
(array([5]),)
(array([2, 5, 8]),)


In [83]:
# Numpy searchsorted() Method
# It present in the numpy library of python used to deal with sorted arrays. The function is used to determine the index of an element while inserting it into a sorted array.


pyarr=np.array([1,10,11,15,21])
pyelement=np.searchsorted(pyarr,17)
print(pyelement) # [1,10,11,15,17,21] 17 is sorted in between 15 and 21 thats the index 4
arr2=np.insert(pyarr,4,20)
print(arr2)

4
[ 1 10 11 15 20 21]


In [98]:
import numpy as np
nparr=np.array([1,2,3,3,5,6])
print(nparr)
print(f"Type : {type(nparr)}")
normalArr_list=[1,2,3,3,5,6]
print(normalArr_list)
print(f"Type : {type(normalArr_list)}")


PyArr=np.searchsorted(normalArr_list, 3)
print(PyArr)
print()
PyArr=np.searchsorted([1,2,3,3,5,6], 3,side='right')
print(PyArr)
print()
PyArr=np.searchsorted([1,2,3,3,5,6], 3,side='left')
print(PyArr)

[1 2 3 3 5 6]
Type : <class 'numpy.ndarray'>
[1, 2, 3, 3, 5, 6]
Type : <class 'list'>
2

4

2


In [93]:
import numpy as np
print(np.searchsorted(['apple','vinegar','zucchini'], 'bananas'))
print(np.searchsorted(['apple','vinegar','zucchini'], 'Bananas'))


1
0


In [101]:
import numpy as np
PyArr = [[1,2,6],[3,4,10]]
print(PyArr[0])
print(np.searchsorted(PyArr[0], 2)) 
print(PyArr[1])
print(np.searchsorted(PyArr[1], 10))

[1, 2, 6]
1
[3, 4, 10]
2


In [108]:
pyarr = np.array([[1,2,6],[3,4,10]])
print(pyarr)
pyarr1=pyarr.flatten()
print(pyarr1)
pyarr1.sort()
print(pyarr1)
print(np.searchsorted(pyarr1,10))

[[ 1  2  6]
 [ 3  4 10]]
[ 1  2  6  3  4 10]
[ 1  2  3  4  6 10]
5


In [109]:
import numpy as np
a= np.array([(1,2,3),(3,4,5)])
print(a.sum(axis=0))
print(a.sum(axis=1))

[4 6 8]
[ 6 12]


In [110]:
import numpy as np
Arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(Arr)) 


['apple' 'banana' 'cherry']


In [ ]:
import numpy as np
Arr = np.array([True, False, True])
print(np.sort(Arr))


[False  True  True]


In [112]:
# Sorting a 2-D Array
# If you use the sort() method on a 2-D array, both arrays will be sorted:

import numpy as np
Arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(Arr)) 


[[2 3 4]
 [0 1 5]]


In [ ]:
import numpy as np 
PyArr1 = np.array([[17, 15], [10, 25]]) 
PyArr2 = np.sort(PyArr1)
print(PyArr2)
print()
PyArr2 = np.sort(PyArr1, axis =0)
print(PyArr2)


[[15 17]
 [10 25]]

[[10 15]
 [17 25]]


In [118]:
# NOTE:0 means we have to check column wise,1 means we have to check rows wise.

import numpy as np 
PyArr1 = np.array([[199, 15], [20, 18]]) 
print(PyArr1)
PyArr2= np.sort(PyArr1, axis = None) 
print(PyArr2) 

[[199  15]
 [ 20  18]]
[ 15  18  20 199]


In [ ]:
pyarr=np.array([('chinnu',100),('puppy',200)])
print(pyarr)
print(type(pyarr))

print()

pyDatatype=np.dtype([('name','S10'),('marks',int)])
pyarr=np.array([('chinnu',100),('puppy',200)],dtype=pyDatatype)
print(pyarr)
print(type(pyarr))
print()
sortedpyar=np.sort(pyarr,order='name')
print(sortedpyar)


[['chinnu' '100']
 ['puppy' '200']]
<class 'numpy.ndarray'>

[(b'chinnu', 100) (b'puppy', 200)]
<class 'numpy.ndarray'>

[(b'chinnu', 100) (b'puppy', 200)]
